import { parseAbi } from "viem";

export const erc20Abi = parseAbi([
  "function allowance(address owner, address spender) view returns (uint256)",
  "function approve(address spender, uint256 amount) returns (bool)",
  "function balanceOf(address account) view returns (uint256)",
  "function decimals() view returns (uint8)",
  "function symbol() view returns (string)",
  "function transfer(address to, uint256 amount) returns (bool)",
]);

export const wstEthAbi = parseAbi([
  "function allowance(address owner, address spender) view returns (uint256)",
  "function approve(address spender, uint256 amount) returns (bool)",
  "function balanceOf(address account) view returns (uint256)",
  "function decimals() view returns (uint8)",
  "function symbol() view returns (string)",
  "function transfer(address to, uint256 amount) returns (bool)",
  "function getStETHByWstETH(uint256 wstETHAmount) view returns (uint256)",
  "function getWstETHByStETH(uint256 stETHAmount) view returns (uint256)",
]);

export const ringfenceAbi = parseAbi([
  "event Deposited(address indexed owner, uint256 wstETHAmount, uint256 newBaseline)",
  "event PrincipalWithdrawn(address indexed owner, address indexed recipient, uint256 wstETHAmount, uint256 withdrawnValue, uint256 newBaseline)",
  "event Claimed(address indexed agent, address indexed recipient, uint256 amount)",
  "event AgentSet(address indexed newAgent)",
  "event RecipientWhitelistUpdated(address indexed recipient, bool allowed)",
  "event PerTxCapUpdated(uint256 newCap)",
  "function MAX_RATE_AGE() view returns (uint256)",
  "function owner() view returns (address)",
  "function agent() view returns (address)",
  "function wstETH() view returns (address)",
  "function principalBaseline() view returns (uint256)",
  "function getEffectivePrincipalBaseline() view returns (uint256)",
  "function getCurrentPositionValue() view returns (uint256)",
  "function getClaimableAmount() view returns (uint256)",
  "function isRecipientWhitelisted(address recipient) view returns (bool)",
  "function perTxCap() view returns (uint256)",
  "function setAgent(address newAgent)",
  "function deposit(uint256 amount)",
  "function withdrawPrincipal(uint256 amount, address recipient)",
  "function setRecipientWhitelist(address recipient, bool allowed)",
  "function setPerTxCap(uint256 newCap)",
  "function claim(uint256 amount, address recipient)",
]);

export const demoHarnessAbi = parseAbi([
  "event Deposited(address indexed owner, uint256 wstETHAmount, uint256 newBaseline)",
  "event PrincipalWithdrawn(address indexed owner, address indexed recipient, uint256 wstETHAmount, uint256 withdrawnValue, uint256 newBaseline)",
  "event Claimed(address indexed agent, address indexed recipient, uint256 amount)",
  "event AgentSet(address indexed newAgent)",
  "event RecipientWhitelistUpdated(address indexed recipient, bool allowed)",
  "event PerTxCapUpdated(uint256 newCap)",
  "event DemoSpendableDeltaGranted(uint256 deltaStETH, uint256 newTotal)",
  "event DemoSpendableDeltaReset()",
  "function MAX_RATE_AGE() view returns (uint256)",
  "function owner() view returns (address)",
  "function agent() view returns (address)",
  "function wstETH() view returns (address)",
  "function principalBaseline() view returns (uint256)",
  "function getEffectivePrincipalBaseline() view returns (uint256)",
  "function getCurrentPositionValue() view returns (uint256)",
  "function getClaimableAmount() view returns (uint256)",
  "function isRecipientWhitelisted(address recipient) view returns (bool)",
  "function perTxCap() view returns (uint256)",
  "function setAgent(address newAgent)",
  "function deposit(uint256 amount)",
  "function withdrawPrincipal(uint256 amount, address recipient)",
  "function setRecipientWhitelist(address recipient, bool allowed)",
  "function setPerTxCap(uint256 newCap)",
  "function claim(uint256 amount, address recipient)",
  "function demoSpendableDeltaStETH() view returns (uint256)",
  "function demoGrantSpendableDelta(uint256 deltaStETH)",
  "function demoResetSpendableDelta()",
]);
